function compareLists(list1, list2) {
    return list1.map(item1 => {
        return {
            item: item1,
            found: list2.some(item2 => item2.includes(item1))
        };
    });
}

// Exemplo de uso:
const list1 = [
    "Atenção, somente para fluxos que já possuam chamadas API devido ao Status 'avançado' que gera maior custo mensal.",
    "Carteira a ser implementada em chamadas API.",
    "Estes módulos automatizam a segunda tentativa de requisição da API. Registrando um evento de erro se o contato chegar em Módulo Erro Persistente API.",
    "Facilite o uso do @identificadororiginal usando {{aguardar}} no 'Ir Para'.",
    "Informações de uso {{Pergunta Atual}}.",
    "Informações de uso da variável {{fluxo}}.",
    "Informações de uso Pergunta Atual",
    "Informações de uso.",
    "Módulo de Input Inesperado, termos não previstos.",
    "Salve linha para facilitar eventuais alterações de um telefone. Use {{linha}} onde desejar aplicar o conteúdo.",
    "Salve o 0800 para facilitar eventuais alterações. Use {{_0800}} onde desejar aplicar o conteúdo.",
    "Salve o domínio da URL/endpoint e facilite alterações. ?O protocolo 'https://' tem que ficar na ação de chamada API.",
    "Salve o Link  para facilitar eventuais alterações. Utilize {{site}} onde desejar aplicar o conteúdo.",
    "Salve o título dos botões/listas para facilitar alterações. Não use asteriscos ou underline. Alguns emojis não funcionam. Não ultrapasse caracteres",
    "Zera Abandono. Essa variável reinicia as passagens do fluxo de Abanono_Bot",
    "Adiciona Quantidade de Erros API",
    "Agradece Avaliação Negativa Atendente",
    "Agradece Avaliação Negativa Chatbot",
    "Agradece Avaliação Positiva Atendente",
    "Agradece Avaliação Positiva Chatbot",
    "Agradecimento Nota Negativa",
    "API Cartao Card",
    "API Enviar Agendamento",
    "API Gerar Token",
    "API Gerar Token Agendamento",
    "API Gerar Token Reporta Problema Agendamento",
    "API Retorna Problema Agendamento",
    "Boas Vindas",
    "Botoes inatividade",
    "Conteudo Nome Sem Valor",
    "Conteúdo Tipo Agendamento",
    "Define Contato Em Chatbot",
    "Define Contato na Operacao",
    "Dispara HSM Alerta Geral",
    "DISPARAR AVALIAÇÃO",
    "Enviar Mensagem Erro Botões",
    "Enviar Mensagem Erro CPF",
    "Enviar Mensagem Erro Lista",
    "Essa variável salva o user fidelizado. E pode ser usada para enviar a um contato específico. em casos de retenção no chatbot.",
    "Esta verificação precia estar acima do Módulo 'Verifica Retorno Abandono'.",
    "Evento Registra Horario Informado",
    "Evitar que um contato em atendimento utilize comandos.",
    "Evitar que um contato que inicia a conversa com uma mídia vá ao módulo de erro, pois neste módulo é utilizada a var Pergunta Atual, a qual não existe ainda.",
    "Fluxo Aeronave",
    "Fluxo Agendamento",
    "Fluxo Aviation Card",
    "Fluxo Confirma Combustível",
    "Fluxo Confirmar Dados Abastecimento",
    "Fluxo Dados de Desenvolvimento",
    "Fluxo Editar Escolhas",
    "Fluxo Infroma Cartão",
    "Fluxo Inicial",
    "Fluxo Saudação",
    "Fluxo Seleciona Cartão",
    "Fluxo Solicita Prefixo",
    "Fluxo Solicita Tipo Horário",
    "Fluxo Tipo Abastecimento",
    "Fluxo Valida Hangar Preenchido",
    "Fluxo Verifica Transbordo",
    "Gerar Token",
    "INFORMAR SOLICITANTE SOBRE ACEITE",
    "INFORMAR USUÁRIO AGENDAMENTO RESOLVIDO",
    "INFORMAR USUÁRIO NOVO AGENDAMENTO",
    "INFORMAR USUÁRIO PROBLEMA REPORTADO",
    "Inicia Contagem Erro Input",
    "Lista Avaliação Chatbot",
    "looping adiciona data",
    "Mensagem Erro Persistente API",
    "Mensagem Erro Persistente Input",
    "Mensagem Feriado",
    "Mensagem Transbordo em Expediente",
    "Menu Apresenta Configurações Feriado",
    "Menu Botões Confirmar Combustível",
    "Menu Cartão Localizado",
    "Menu Cofirma Informações Abastecimento",
    "Menu Como Quer Viajar",
    "Menu Confirma Nome",
    "Menu Confirmar Resumo Imediato",
    "Menu Datas Viagem",
    "Menu Fluxo Aviation",
    "Menu Hangar",
    "Menu Hangar Abastecido",
    "Menu Informar Prefixo",
    "Menu Modificar Escolhas",
    "Menu Seleciona Combustível",
    "Menu Solicita Tipo de Horários",
    "Módulo Algo Mais",
    "Módulo Avaliação Atendente",
    "Módulo Avaliação ChatBot",
    "Módulo Configura Feriado",
    "Módulo Definições Feriado",
    "Módulo Edita Datas Feriados",
    "Módulo Edita Horários Feriados",
    "Módulo Encerrar Conversa",
    "Módulo Erro API",
    "Módulo Erro Áudio",
    "Módulo Erro Avaliação",
    "Módulo Erro Botões",
    "Módulo Erro CPF",
    "Módulo Erro Documento"
];

const list2 = [
    "Solicita Horário Início Expediente",
    "@identificadororiginal",
    "{{aguardar}}",
    "{{API Atual}}",
    "{{Pergunta Atual}}",
    "Adiciona Quantidade de Erros API",
    "API Enviar Agendamento",
    "Conteudo Nome Sem Valor",
    "Conteúdo Tipo Agendamento",
    "Evento Registra Horario Informado",
    "Fluxo Aeronave",
    "Fluxo Agendamento",
    "Fluxo Aviation Card",
    "Fluxo Confirma Combustível",
    "Fluxo Confirmar Dados Abastecimento",
    "Fluxo Dados de Desenvolvimento",
    "Fluxo Editar Escolhas",
    "Fluxo Infroma Cartão",
    "Fluxo Inicial",
    "Fluxo Saudação",
    "Fluxo Solicita Prefixo",
    "Fluxo Termos Fluxo",
    "Fluxo Tipo Abastecimento",
    "Fluxo Valida Hangar Preenchido"
];

const result = compareLists(list1, list2);
console.log(result);